### ISSUE TITLE
java.lang.NumberFormatException: Invalid int: ""

### ISSUE THREAD

**Issue by KIDNG** [geftimov/android-patternview#11]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.xxx/com.xxx.xxx.view.activity.xxxActivity}: java.lang.NumberFormatException: Invalid int: ""
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:130)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:137)
                                                     at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:511)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: java.lang.NumberFormatException: Invalid int: ""
                                                     at java.lang.Integer.invalidInt(Integer.java:138)
                                                     at java.lang.Integer.parseInt(Integer.java:359)
                                                     at java.lang.Integer.parseInt(Integer.java:332)
                                                     at java.lang.Integer.valueOf(Integer.java:490)
                                                     at com.eftimoff.patternview.utils.CellUtils.stringToPattern(CellUtils.java:36)
                                                     at com.eftimoff.patternview.PatternView.onRestoreInstanceState(PatternView.java:966)
                                                     at android.view.View.dispatchRestoreInstanceState(View.java:11910)
                                                     at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2590)
                                                     at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2590)
                                                     at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2590)
                                                     at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2590)
                                                     at android.view.View.restoreHierarchyState(View.java:11888)
                                                     at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1608)
                                                     at android.app.Activity.onRestoreInstanceState(Activity.java:928)
                                                     at android.app.Activity.performRestoreInstanceState(Activity.java:900)
                                                     at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1130)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2037)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:130) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                     at android.os.Looper.loop(Looper.java:137) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:511) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                     at dalvik.system.NativeStart.main(Native Method)

**Comment by geftimov** [comment]
This should be an old version of the code. Can you specify which version did you use?
